// packages/rich-text-solid-renderer/src/nodes/BlockQuote.tsx

import { Component, JSXElement } from "solid-js";
import { attrsToStyle } from "../transformer/attrsToStyle";

const BlockQuote: Component<{ node: any; children: JSXElement }> = ({ children, node: { attrs } }) => (
  <blockquote style={attrsToStyle(attrs)}>{children}</blockquote>
);

export default BlockQuote;

// packages/rich-text-vue-renderer/src/lib/nodes/BlockQuote.vue
<script>
import { attrsToStyle } from "../transformer/attrsToStyle";

export default {
  name: "BlockQuote",
  props: {
    node: { attrs: Object },
  },
  methods: {
    attrsToStyle,
  },
};
</script>

<template>
  <blockquote :style="attrsToStyle(node.attrs)">
    <slot />
  </blockquote>
</template>
