// packages/rich-text-qwik-renderer/src/components/node/code-block/CodeBlock.tsx
import { component$, Slot, useStylesScoped$ } from "@builder.io/qwik";
import { attrsToStyle } from "../../transformer/attrsToStyle";
import CodeBlockStyles from "./CodeBlock.css?inline";

const CodeBlock = component$<{ node: any }>(({ node }) => {
  useStylesScoped$(CodeBlockStyles);
  return (
    <pre style={attrsToStyle(node?.attrs)}>
      <Slot />
    </pre>
  );
});

export default CodeBlock;

// packages/rich-text-vue-renderer/src/lib/nodes/CodeBlock.vue
<script>
import { attrsToStyle } from "../transformer/attrsToStyle";

export default {
  name: "CodeBlock",
  props: {
    node: { attrs: Object },
    connections: Array,
  },
  methods: {
    attrsToStyle,
  },
};
</script>

<template>
  <pre :style="attrsToStyle(node.attrs)"><slot /></pre>
</template>
