// packages/rich-text-qwik-renderer/src/components/node/OrderedList.tsx
import { component$, Slot } from "@builder.io/qwik";
import { attrsToStyle } from "../transformer/attrsToStyle";

interface IOrdererdList {
  node: any;
}

export default component$<IOrdererdList>(({ node: { attrs } }) => {
  return (
    <ol style={attrsToStyle(attrs)}>
      <Slot />
    </ol>
  );
});

// packages/rich-text-vue-renderer/src/lib/nodes/OrderedList.vue
<script>
import { attrsToStyle } from "../transformer/attrsToStyle";

export default {
  name: "OrderedList",
  props: {
    node: { attrs: Object },
    connections: Array,
  },
  methods: {
    attrsToStyle,
  },
};
</script>

<template>
  <ol :style="attrsToStyle(node.attrs)">
    <slot />
  </ol>
</template>
