// packages/rich-text-svelte-renderer/src/lib/nodes/Text.svelte
<script lang="ts">
	export let node: any;
	// type Marks = 'bold' | 'italic' | 'strike' | 'link' | 'code';
</script>

{#if node.marks && node.marks[0]}
	{#if node.marks[0].type === 'bold'}
		<strong>
			<svelte:self node={{ ...node, marks: node.marks.shift() }} />
		</strong>
    {:else if node.marks[0].type === 'italic'}
		<em>
			<svelte:self node={{ ...node, marks: node.marks.shift() }} />
		</em>
    {:else if node.marks[0].type === 'strike'}
		<s>
			<svelte:self node={{ ...node, marks: node.marks.shift() }} />
		</s>
    {:else if node.marks[0].type === 'code'}
		<code>
      <svelte:self node={{ ...node, marks: node.marks.shift() }} />
		</code>
    {:else if node.marks[0].type === 'link'}
    <a href={node.marks[0].attrs?.href} target={node.marks[0].attrs?.target}>
      <svelte:self node={{ ...node, marks: node.marks.slice(1) }} />
    </a>
    {:else }
    unknown mark type: {node.marks[0].type}
	{/if}
  {:else }
  {node.text}
  <slot></slot>
{/if}

// packages/rich-text-vue-renderer/src/lib/nodes/Text.vue
<script>
import { attrsToStyle } from "../transformer/attrsToStyle";

export default {
  name: "Text",
  props: {
    node: Object,
    connections: Array,
  },
  methods: {
    attrsToStyle,
  },
};
</script>

<template>
  <template v-if="node.marks && node.marks[0]">
    <strong v-if="node.marks[0].type === 'bold'">
      <Text :node="{ ...node, marks: node.marks.slice().shift() }" />
    </strong>

    <em v-else-if="node.marks[0].type === 'italic'">
      <Text :node="{ ...node, marks: node.marks.slice().shift() }" />
    </em>

    <s v-else-if="node.marks[0].type === 'strike'">
      <Text :node="{ ...node, marks: node.marks.slice().shift() }" />
    </s>

    <code v-else-if="node.marks[0].type === 'code'">
      <Text :node="{ ...node, marks: node.marks.slice().shift() }" />
    </code>

    <a
      v-else-if="node.marks[0].type === 'link'"
      :href="node.marks[0].attrs?.href"
      :target="node.marks[0].attrs?.target"
    >
      <Text :node="{ ...node, marks: node.marks.slice(1) }" />
    </a>
  </template>

  <template v-else>{{ node.text }}</template>
</template>
