// packages/rich-text-vue-renderer/src/RichtextRenderer.vue
<script setup>
import { defineProps } from "vue";
import BlockQuoteVue from "./nodes/BlockQuote.vue";
import BulletListVue from "./nodes/BulletList.vue";
import CodeBlockVue from "./nodes/CodeBlock.vue";
import DocVue from "./nodes/Doc.vue";
import HardBreakVue from "./nodes/HardBreak.vue";
import HeadingVue from "./nodes/Heading.vue";
import IFrameVue from "./nodes/IFrame.vue";
import ListItemVue from "./nodes/ListItem.vue";
import OrderedListVue from "./nodes/OrderedList.vue";
import ParagraphVue from "./nodes/Paragraph.vue";
import TableVue from "./nodes/Table.vue";
import TableCellVue from "./nodes/TableCell.vue";
import TableHeaderVue from "./nodes/TableHeader.vue";
import TableRowVue from "./nodes/TableRow.vue";
import TextVue from "./nodes/Text.vue";

const props = defineProps({
  node: Object,
  blockMap: Map,
});

const DEFAULT_BLOCK_MAP = {
  doc: DocVue,
  hardBreak: HardBreakVue,
  paragraph: ParagraphVue,
  codeBlock: CodeBlockVue,
  blockquote: BlockQuoteVue,
  bulletList: BulletListVue,
  orderedList: OrderedListVue,
  listItem: ListItemVue,
  heading: HeadingVue,
  iframe: IFrameVue,
  table: TableVue,
  tableRow: TableRowVue,
  tableHeader: TableHeaderVue,
  tableCell: TableCellVue,
  text: TextVue,
  // documentLink: DocumentLink,
};

const BLOCKS = { ...DEFAULT_BLOCK_MAP, ...props?.blockMap };

const getComponent = (type) => {
  return BLOCKS[type];
};
</script>

<template>
  <template v-if="node.content">
    <component
      v-for="(child, index) in node.content"
      :key="`node-${child.type}-${index}`"
      :is="getComponent(child.type)"
      :node="child"
    >
      <RichtextRenderer v-if="child.content" :node="child" />
    </component>
  </template>
  <slot />
</template>

// packages/rich-text-svelte-renderer/src/lib/RichTextRenderer.svelte
<script lang="ts">
	export let node: any;
	export let overwrites: any | undefined = undefined;

	import Doc from '$lib/nodes/Doc.svelte';
	import Paragraph from '$lib/nodes/Paragraph.svelte';
	import Text from '$lib/nodes/Text.svelte';
	import BlockQuote from '$lib/nodes/BlockQuote.svelte';
	import BulletList from '$lib/nodes/BulletList.svelte';
	import OrderedList from '$lib/nodes/OrderedList.svelte';
	import ListItem from '$lib/nodes/ListItem.svelte';
	import Heading from '$lib/nodes/Heading.svelte';
	import DocumentLink from '$lib/nodes/DocumentLink.svelte';
	import IFrame from '$lib/nodes/IFrame.svelte';
	import Table from '$lib/nodes/Table.svelte';
	import TableRow from '$lib/nodes/TableRow.svelte';
	import TableCell from '$lib/nodes/TableCell.svelte';
	import TableHeader from '$lib/nodes/TableHeader.svelte';
	import HardBreak from '$lib/nodes/HardBreak.svelte';
	import CodeBlock from '$lib/nodes/CodeBlock.svelte';

	const DEFAULT_BLOCK_MAP: any = {
		doc: Doc,
		paragraph: Paragraph,
		hardBreak: HardBreak,
		codeBlock: CodeBlock,
		text: Text,
		blockquote: BlockQuote,
		listItem: ListItem,
		bulletList: BulletList,
		orderedList: OrderedList,
		heading: Heading,
		iframe: IFrame,
		table: Table,
		tableHeader: TableHeader,
		tableRow: TableRow,
		tableCell: TableCell,
		documentLink: DocumentLink
	};

	const blockMap = {
		...DEFAULT_BLOCK_MAP,
		...(overwrites || {})
	};
</script>

{#if node.content}
	{#each node.content as child}
		<svelte:component this={blockMap[child.type]} node={child}>
			{#if child.content}
				<svelte:self node={child} />
			{/if}
		</svelte:component>
	{/each}
{/if}
<slot />
