// packages/rich-text-qwik-renderer/src/components/renderer/RichTextRenderer.tsx
import { component$ } from "@builder.io/qwik";
import BlockQuote from "../node/block-quote/BlockQuote";
import CodeBlock from "../node/code-block/CodeBlock";
import Heading from "../node/heading/Heading";
import Iframe from "../node/iframe/Iframe";
import BulletList from "../node/list/BulletList";
import OrderedList from "../node/list/OrderedList";
import Paragraph from "../node/paragraph/Paragraph";
import Table from "../node/table/Table";
import Text from "../node/text/Text";

interface IRenderer {
  json?: any;
}

export type ElementType =
  | "doc"
  | "hardBreak"
  | "paragraph"
  | "codeBlock"
  | "blockquote"
  | "bulletList"
  | "orderedList"
  | "listItem"
  | "heading"
  | "iframe"
  | "table"
  | "tableHeader"
  | "tableRow"
  | "tableCell"
  | "documentLink"
  | "text";

export const RichTextRenderer = component$<IRenderer>(({ json }) => {
  if (json?.type !== "doc") return <>json object must be of type:"doc"</>;

  return (
    <>
      {json?.content?.map((element: any, elementIndex: number) => {
        switch (element.type) {
          case "paragraph":
            return (
              <Paragraph key={`pc-${elementIndex}`} attrs={element?.attrs}>
                <Text nodesArr={element?.content} />
              </Paragraph>
            );
          case "heading":
            return (
              <Heading
                key={`pc-${elementIndex}`}
                level={element.attrs.level}
                nodesArr={element.content}
                attrs={element.attrs}
              />
            );
          case "orderedList":
            return <OrderedList node={element} key={`pc-${elementIndex}`} />;
          case "bulletList":
            return <BulletList node={element} key={`pc-${elementIndex}`} />;
          case "blockquote":
            return <BlockQuote node={element} />;
          case "codeBlock":
            return (
              <CodeBlock node={element}>
                <Text nodesArr={element.content} />
              </CodeBlock>
            );
          case "table":
            return <Table node={element} />;
          case "iframe":
            return <Iframe node={element} />;
          default:
            return <>Unknown TYPE</>;
        }
      })}
    </>
  );
});

// packages/rich-text-svelte-renderer/src/lib/RichTextRenderer.svelte
<script lang="ts">
	export let node: any;
	export let overwrites: any | undefined = undefined;

	import Doc from '$lib/nodes/Doc.svelte';
	import Paragraph from '$lib/nodes/Paragraph.svelte';
	import Text from '$lib/nodes/Text.svelte';
	import BlockQuote from '$lib/nodes/BlockQuote.svelte';
	import BulletList from '$lib/nodes/BulletList.svelte';
	import OrderedList from '$lib/nodes/OrderedList.svelte';
	import ListItem from '$lib/nodes/ListItem.svelte';
	import Heading from '$lib/nodes/Heading.svelte';
	import DocumentLink from '$lib/nodes/DocumentLink.svelte';
	import IFrame from '$lib/nodes/IFrame.svelte';
	import Table from '$lib/nodes/Table.svelte';
	import TableRow from '$lib/nodes/TableRow.svelte';
	import TableCell from '$lib/nodes/TableCell.svelte';
	import TableHeader from '$lib/nodes/TableHeader.svelte';
	import HardBreak from '$lib/nodes/HardBreak.svelte';
	import CodeBlock from '$lib/nodes/CodeBlock.svelte';

	const DEFAULT_BLOCK_MAP: any = {
		doc: Doc,
		paragraph: Paragraph,
		hardBreak: HardBreak,
		codeBlock: CodeBlock,
		text: Text,
		blockquote: BlockQuote,
		listItem: ListItem,
		bulletList: BulletList,
		orderedList: OrderedList,
		heading: Heading,
		iframe: IFrame,
		table: Table,
		tableHeader: TableHeader,
		tableRow: TableRow,
		tableCell: TableCell,
		documentLink: DocumentLink
	};

	const blockMap = {
		...DEFAULT_BLOCK_MAP,
		...(overwrites || {})
	};
</script>

{#if node.content}
	{#each node.content as child}
		<svelte:component this={blockMap[child.type]} node={child}>
			{#if child.content}
				<svelte:self node={child} />
			{/if}
		</svelte:component>
	{/each}
{/if}
<slot />
