// packages/rich-text-svelte-renderer/src/lib/nodes/Heading.svelte
<script lang="ts">
	import { attrsToStyle } from '../transformer/attrsToStyle';

	export let node: any;

  const attrs = node.attrs;
  const level = node.attrs?.level;
</script>

{#if level === 1}
  <h1 style={attrsToStyle(attrs)}><slot /></h1>
{:else if level === 2}
  <h2 style={attrsToStyle(attrs)}><slot /></h2>
{:else if level === 3}
  <h3 style={attrsToStyle(attrs)}><slot /></h3>
{:else if level === 4}
  <h4 style={attrsToStyle(attrs)}><slot /></h4>
{:else if level === 5}
  <h5 style={attrsToStyle(attrs)}><slot /></h5>
{:else if level === 6}
  <h6 style={attrsToStyle(attrs)}><slot /></h6>
{/if}

// packages/rich-text-qwik-renderer/src/components/node/Heading.tsx
import { component$, Slot } from "@builder.io/qwik";
// import type { IntrinsicHTMLElements } from "@builder.io/qwik/jsx-runtime";
import { attrsToStyle } from "../transformer/attrsToStyle";

interface IHeadingNode {
  attrs: any;
  level: number;
}
interface IHeader {
  node: IHeadingNode;
}

export default component$<IHeader>(({ node: { attrs } }) => {
  const level = attrs.level;
  const CustomTag = `h${level}` as any;
  return (
    <CustomTag style={attrsToStyle(attrs)}>
      <Slot />
    </CustomTag>
  );
});
