// packages/rich-text-svelte-renderer/src/lib/nodes/Heading.svelte
<script lang="ts">
	import { attrsToStyle } from '../transformer/attrsToStyle';

	export let node: any;

  const attrs = node.attrs;
  const level = node.attrs?.level;
</script>

{#if level === 1}
  <h1 style={attrsToStyle(attrs)}><slot /></h1>
{:else if level === 2}
  <h2 style={attrsToStyle(attrs)}><slot /></h2>
{:else if level === 3}
  <h3 style={attrsToStyle(attrs)}><slot /></h3>
{:else if level === 4}
  <h4 style={attrsToStyle(attrs)}><slot /></h4>
{:else if level === 5}
  <h5 style={attrsToStyle(attrs)}><slot /></h5>
{:else if level === 6}
  <h6 style={attrsToStyle(attrs)}><slot /></h6>
{/if}

// packages/rich-text-react-renderer/src/nodes/Heading.tsx
import React, { FC } from "react";
import { attrsToStyle } from "../transformer/attrsToStyle";

const Heading: FC<{ node: any }> = ({ node, children }) => {
  const attrs = node.attrs;
  const level = node.attrs.level;

  switch (level) {
    case 1:
      return <h1 style={attrsToStyle(attrs)}>{children}</h1>;
    case 2:
      return <h2 style={attrsToStyle(attrs)}>{children}</h2>;
    case 3:
      return <h3 style={attrsToStyle(attrs)}>{children}</h3>;
    case 4:
      return <h4 style={attrsToStyle(attrs)}>{children}</h4>;
    case 5:
      return <h5 style={attrsToStyle(attrs)}>{children}</h5>;
    case 6:
      return <h6 style={attrsToStyle(attrs)}>{children}</h6>;
  }

  return <></>;
};

export default Heading;
