// packages/rich-text-svelte-renderer/src/lib/nodes/IFrame.svelte
<script lang="ts">
	import { attrsToStyle } from '../transformer/attrsToStyle';
	export let node: any;
	const attrs = node.attrs;
</script>

<iframe
	style={node?.attrs ? attrsToStyle(node.attrs) : undefined}
	src={attrs.src}
	allow={attrs.allow}
	title={attrs.title}
	frameBorder={attrs.frameborder}
	height={attrs.height}
	width={attrs.width}
	allowFullScreen={attrs.allowfullscreen}><slot /></iframe
>

// packages/rich-text-react-renderer/src/nodes/IFrame.tsx
import React, { FC } from "react";
import { attrsToStyle } from "../transformer/attrsToStyle";

const IFrame: FC<{ node: any }> = ({ node: { attrs } }) => (
  <iframe
    style={attrsToStyle(attrs)}
    src={attrs.src}
    allow={attrs.allow}
    title={attrs.title}
    frameBorder={attrs.frameborder}
    height={attrs.height}
    width={attrs.width}
    allowFullScreen={attrs.allowfullscreen}
  />
);

export default IFrame;
