// packages/rich-text-qwik-renderer/src/RichTextRenderer.tsx
import { component$ } from "@builder.io/qwik";
import { documentRenderer } from "./renderer";

export const RichTextRenderer = component$<{
  node: any;
  overwrites?: any;
}>(({ node, overwrites }) => {
  if (!node) {
    return null;
  }
  const renderer = documentRenderer((overwrites as any) || {});
  return <>{renderer(node)}</>;
});

// packages/rich-text-react-renderer/src/RichTextRenderer.tsx
import React from "react";
import { documentRenderer, ElementType } from "./renderer";

export const RichTextRenderer: React.FC<{
  node: any;
  overwrites?: Partial<Record<ElementType, React.FC<{ node: any }>> | null>;
}> = ({ node, overwrites }) => {
  if (!node) {
    return null;
  }
  const renderer = documentRenderer((overwrites as any) || {});
  return <>{renderer(node)}</>;
}
