// packages/rich-text-qwik-renderer/src/renderer.tsx
import BlockQuote from "./components/node/BlockQuote";
import BulletList from "./components/node/BulletList";
import CodeBlock from "./components/node/CodeBlock";
import Doc from "./components/node/Doc";
import DocumentLink from "./components/node/DocumentLink";
import HardBreak from "./components/node/HardBreak";
import Heading from "./components/node/Heading";
import IFrame from "./components/node/IFrame";
import ListItem from "./components/node/ListItem";
import OrderedList from "./components/node/OrderedList";
import Paragraph from "./components/node/Paragraph";
import Table from "./components/node/Table";
import TableCel from "./components/node/TableCell";
import TableHeader from "./components/node/TableHeader";
import TableRow from "./components/node/TableRow";
import Text from "./components/node/Text";

export type ElementType =
  | "doc"
  | "hardBreak"
  | "paragraph"
  | "codeBlock"
  | "blockquote"
  | "bulletList"
  | "orderedList"
  | "listItem"
  | "heading"
  | "iframe"
  | "table"
  | "tableHeader"
  | "tableRow"
  | "tableCell"
  | "documentLink"
  | "text";

export const DEFAULT_BLOCK_MAP: any = {
  doc: Doc,
  hardBreak: HardBreak,
  paragraph: Paragraph,
  codeBlock: CodeBlock,
  blockquote: BlockQuote,
  bulletList: BulletList,
  orderedList: OrderedList,
  listItem: ListItem,
  heading: Heading,
  iframe: IFrame,
  table: Table,
  tableRow: TableRow,
  tableHeader: TableHeader,
  tableCell: TableCel,
  text: Text,
  documentLink: DocumentLink,
};

export const documentRenderer = (blockMap: any) => {
  const BLOCKS = { ...DEFAULT_BLOCK_MAP, ...blockMap };

  const renderNode = (
    currNode: any,
    currNodeIndex?: number,
    parentPath?: string
  ) => {
    const Element = BLOCKS[currNode.type];

    if (!Element) {
      console.log("renderNode -> missing node type:", currNode.type);
      return null;
    }

    const path =
      (parentPath ? parentPath + "-" : "") +
      (typeof currNodeIndex === "number" ? currNodeIndex : "");

    return (
      <Element
        key={`node-${currNode.type}-${path}`}
        node={currNode}
        path={path}
      >
        {currNode.content?.map((node: any, index: any) =>
          renderNode(node, index, path)
        )}
      </Element>
    );
  };

  return renderNode;
};

export default documentRenderer(DEFAULT_BLOCK_MAP);

// packages/rich-text-solid-renderer/src/renderer.tsx
import BlockQuote from "./nodes/BlockQuote";
import BulletList from "./nodes/BulletList";
import CodeBlock from "./nodes/CodeBlock";
import Doc from "./nodes/Doc";
import DocumentLink from "./nodes/DocumentLink";
import HardBreak from "./nodes/HardBreak";
import Heading from "./nodes/Heading";
import IFrame from "./nodes/IFrame";
import ListItem from "./nodes/ListItem";
import OrderedList from "./nodes/OrderedList";
import Paragraph from "./nodes/Paragraph";
import Table from "./nodes/Table";
import TableCel from "./nodes/TableCell";
import TableHeader from "./nodes/TableHeader";
import TableRow from "./nodes/TableRow";
import Text from "./nodes/Text";
import { Component } from "solid-js";

export type ElementType =
  | "doc"
  | "hardBreak"
  | "paragraph"
  | "codeBlock"
  | "blockquote"
  | "bulletList"
  | "orderedList"
  | "listItem"
  | "heading"
  | "iframe"
  | "table"
  | "tableHeader"
  | "tableRow"
  | "tableCell"
  | "documentLink"
  | "text";

export const DEFAULT_BLOCK_MAP: Record<
  ElementType,
  any
> = {
  doc: Doc,
  hardBreak: HardBreak,
  paragraph: Paragraph,
  codeBlock: CodeBlock,
  blockquote: BlockQuote,
  bulletList: BulletList,
  orderedList: OrderedList,
  listItem: ListItem,
  heading: Heading,
  iframe: IFrame,
  table: Table,
  tableRow: TableRow,
  tableHeader: TableHeader,
  tableCell: TableCel,
  text: Text,
  documentLink: DocumentLink,
};

export const documentRenderer = (
  blockMap: Record<ElementType, Component<{ node: any }>>
) => {
  const BLOCKS: any = { ...DEFAULT_BLOCK_MAP, ...blockMap };

  const renderNode = (
    currNode: any,
    currNodeIndex?: number,
    parentPath?: string
  ) => {
    const Element = BLOCKS[currNode.type];

    if (!Element) {
      console.log("renderNode -> missing node type:", currNode.type);
      return null;
    }

    const path =
      (parentPath ? parentPath + "-" : "") +
      (typeof currNodeIndex === "number" ? currNodeIndex : "");

    return (
      <Element
        key={`node-${currNode.type}-${path}`}
        node={currNode}
        path={path}
      >
        {currNode.content?.map((node: any, index: number) =>
          renderNode(node, index, path)
        )}
      </Element>
    );
  };

  return renderNode;
};

export default documentRenderer(DEFAULT_BLOCK_MAP);
