// packages/rich-text-react-renderer/src/RichTextRenderer.tsx
import React from "react";
import { documentRenderer, ElementType } from "./renderer";

export const RichTextRenderer: React.FC<{
  node: any;
  overwrites?: Partial<Record<ElementType, React.FC<{ node: any }>> | null>;
}> = ({ node, overwrites }) => {
  if (!node) {
    return null;
  }
  const renderer = documentRenderer((overwrites as any) || {});
  return <>{renderer(node)}</>;
}

// packages/rich-text-solid-renderer/src/RichTextRenderer.tsx
import { Component, JSXElement } from "solid-js";
import { documentRenderer, ElementType } from "./renderer";

export const RichTextRenderer: Component<{
  node: any;
  overwrites?: Partial<Record<ElementType, (JSXElement | Component<any> | null)> | null>;
}> = ({ node, overwrites }) => {
  
  if (!node) {
    return null;
  }
  return documentRenderer((overwrites as any) || {})(node)
};
