// packages/rich-text-react-renderer/src/nodes/DocumentLink.tsx
import React, { FC } from "react";

const DocumentLink: FC<{ node: any }> = ({ children, node }) => {
  console.warn("documentLink should be implemented with an overwrite in the richtext");
  return (
    <>
      {node?.attrs?.documentId ?? ""}
      {children}
    </>
  );
};

export default DocumentLink;

// packages/rich-text-svelte-renderer/src/lib/nodes/DocumentLink.svelte
<script lang="ts">
  console.warn("documentLink should be implemented with an overwrite in the richtext");

	export let node: any;
	export let connections: any;

	const connectedType = connections?.find((c: any) => c?.id === node?.attrs?.documentId)?.__typename
</script>
{connectedType ?? ""}
{node?.attrs?.documentId ?? ""}
<slot></slot>
