// packages/rich-text-qwik-renderer/src/components/node/TableCell.tsx
import { component$, Slot } from "@builder.io/qwik";
import { attrsToStyle } from "../transformer/attrsToStyle";

export default component$<{ node: any }>(({ node: { attrs } }) => (
  <td
    colSpan={attrs?.colspan ? attrs?.colspan : undefined}
    rowSpan={attrs?.rowspan ? attrs?.rowspan : undefined}
    style={attrsToStyle(attrs)}
  >
    <Slot />
  </td>
));

// packages/rich-text-svelte-renderer/src/lib/nodes/TableCell.svelte
<script lang="ts">
	import { attrsToStyle } from "../transformer/attrsToStyle";
	export let node: any;
</script>
  <td colspan={ node?.attrs?.colspan ? node?.attrs?.colspan : undefined} rowspan={ node?.attrs?.rowspan ? node?.attrs?.rowspan : undefined} style={(node?.attrs ? attrsToStyle(node.attrs) : undefined) }><slot></slot></td>
