// packages/rich-text-qwik-renderer/src/components/node/block-quote/BlockQuote.tsx
import { component$ } from "@builder.io/qwik";
import { attrsToStyle } from "../../transformer/attrsToStyle";
import Text from "../text/Text";

const BlockQuote = component$<{ node: any }>(({ node }) => {
  return (
    <blockquote style={attrsToStyle(node?.content?.[0]?.attrs)}>
      <Text nodesArr={node?.content?.[0].content} />
    </blockquote>
  );
});

export default BlockQuote;

// packages/rich-text-solid-renderer/src/nodes/BlockQuote.tsx

import { Component, JSXElement } from "solid-js";
import { attrsToStyle } from "../transformer/attrsToStyle";

const BlockQuote: Component<{ node: any; children: JSXElement }> = ({ children, node: { attrs } }) => (
  <blockquote style={attrsToStyle(attrs)}>{children}</blockquote>
);

export default BlockQuote;
