// packages/rich-text-vue-renderer/src/lib/nodes/Table.vue
<script>
import { attrsToStyle } from "../transformer/attrsToStyle";

export default {
  name: "Table",
  props: {
    node: { attrs: Object },
  },
  methods: {
    attrsToStyle,
  },
};
</script>

<template>
  <table :style="attrsToStyle(node.attrs)">
    <tbody>
      <slot />
    </tbody>
  </table>
</template>

// packages/rich-text-solid-renderer/src/nodes/Table.tsx
import { attrsToStyle } from "../transformer/attrsToStyle";
import { Component, JSXElement } from "solid-js";

const Table: Component<{ node: any; children: JSXElement }> = ({ children, node: { attrs } }) => (
  <table>
    <tbody style={attrsToStyle(attrs)}>{children}</tbody>
  </table>
);

export default Table;
